### PR TITLE
Some Updates

### PR DESCRIPTION
**Pull request by sergiomarotco**

### CODE REVIEW

**Comment by fproulx-boostsecurity** [comment]
Thanks for the contribution @sergiomarotco !

At first I thought `victim_has_reviewer_access`  is the same as `victim_has_repo_write_access` because if you have Write you can review by default, but it's good to point out that you can have tighter Branch Protection that would be restricting to a subset of people with write those who can approve. So good catch.

Also, good suggestion for new goal to delete the repo.

Now, can you elaborate on what you meant by `Other_elavation` (typo too) ? What did you have in mind? Same for `Attacker_can_elevate_permissions`, any specific scenarios?

Your `Approve_malicious_PR_from_another_compromised_account` appears to be very similar to my `get_enough_fake_PR_approvals`. Any extra details to help me distinguish between the two ?

**Comment by sergiomarotco** [comment]
`At first I thought victim_has_reviewer_access is the same as victim_has_repo_write_access because if you have Write you can review by default, but it's good to point out that you can have tighter Branch Protection that would be restricting to a subset of people with write those who can approve. So good catch.`
For example, in Azure DevOps Server, it allows you to configure permissions granularly. If this is not the case in Gitlab / Github, do not accept this edit.
image

**Comment by sergiomarotco** [comment]
`Same for Attacker_can_elevate_permissions`
This means granting rights to yourself or another controlled account if you have rights to manage access rights:
\
image

Often in companies, access rights are controlled by individual employees who do not have rights to either change or read. That is, they are only access administrators.

**Comment by sergiomarotco** [comment]
`Other_elavation`
I wanted to group all possible other elevations to myself. If you create a lot of attacks:
1. Elevation of rights to the editor
2. Elevation to Force push
3. Elevation before Bypassing Repository Policies
...
then this greatly increases the size of the tree and the arrows overlap each other, I tried it, it looks ugly

**Comment by sergiomarotco** [comment]
`Your Approve_malicious_PR_from_another_compromised_account appears to be very similar to my get_enough_fake_PR_approvals. Any extra details to help me distinguish between the two ?`
I read your text through a translator, maybe it's the same :)

As I understand it, your "Forge 2nd valid membership with repo write access" attack vector differs from mine in that your "Allow one membership per identity" option implies that the user has two or more legal accounts. In mine, I mean that the hacker compromised one account, but he may not know that the owner of the compromised account may have another legitimate account and the hacker needs to compromise another account of another worker. I also note that in Azure DevOps Server, for example, contributor rights do not allow [by default](https://learn.microsoft.com/en-us/azure/devops/organizations/security/default-git-permissions?bc=%2Fazure%2Fdevops%2Frepos%2Fbreadcrumb%2Ftoc.json&toc=%2Fazure%2Fdevops%2Frepos%2Ftoc.json&view=azure-devops) to approve pull requests or bypass policy:
image

In general, it seemed to me that your vector is about the evil actions of an insider with two accounts and which the security people know about. That is, your version seemed to me more about an insider or a member of the development team who is simply too lazy to wait for the approval of his changes (not with malicious intent). Mine is about the variant of the attack vector through an attack using different accounts of different workers.

**Pull request closed without merging**
